import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Kalam } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import AppProvider from "./Provider";
import { NavBar } from "@/components/landingpage/nav-bar";
import { ScalesContainer } from "@/components/ui/scales";
import Footer from "@/components/landingpage/footer";
import { Container, LayoutContainer } from "@/components/landingpage/container";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kalam = Kalam({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-kalam-variable",
});

export const metadata: Metadata = {
  title: "DevBuilds-Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", inter.variable)}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kalam.variable} antialiased`}
      >
        <AppProvider>
          <NavBar />
          {children}
        </AppProvider>
        <div className="w-full border-t-2 ">
          <LayoutContainer>
            <ScalesContainer
              orientation="diagonal"
              size={12}
              containerClassName="w-full bg-transparent flex items-center justify-center flex-col border-x-2 border-dashed"
            >
              <Container className="border-x-2 border-dashed">
                <Footer />
              </Container>
            </ScalesContainer>
          </LayoutContainer>
        </div>
      </body>
    </html>
  );
}
